/// Nhật ký làm sạch dữ liệu
table Cleaning_Log
	lineageTag: e59e19ed-3143-5a05-9d2d-2a0349441eb3

	column Step
		dataType: string
		lineageTag: 197a1822-a046-564c-a5bb-cb022254c875
		summarizeBy: none
		sourceColumn: Step

		annotation SummarizationSetBy = Automatic

	column Action
		dataType: string
		lineageTag: 027eb29d-1bcc-5595-9c35-95277fc1f9ac
		summarizeBy: none
		sourceColumn: Action

		annotation SummarizationSetBy = Automatic

	column Rows_Affected
		dataType: int64
		formatString: #,##0
		lineageTag: 124bf4de-9f61-5c58-9687-e5af778172e8
		summarizeBy: sum
		sourceColumn: Rows_Affected

		annotation SummarizationSetBy = Automatic

	column Reason
		dataType: string
		lineageTag: 44e6a893-4b51-544b-8301-bcc98cb2b048
		summarizeBy: none
		sourceColumn: Reason

		annotation SummarizationSetBy = Automatic

	column Rows_After
		dataType: int64
		formatString: #,##0
		lineageTag: 22d618fa-2a6e-5374-935f-83ba22e15ac4
		summarizeBy: none
		sourceColumn: Rows_After

		annotation SummarizationSetBy = Automatic

	column Log_Order
		dataType: int64
		formatString: 0
		lineageTag: 2e597ac2-c12f-5a6e-92c9-f83b9aa3c557
		summarizeBy: none
		sourceColumn: Log_Order

		annotation SummarizationSetBy = Automatic

	partition Cleaning_Log = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(DataFile), null, true),
				    Cleaning_Log = Source{[Item="Cleaning_Log",Kind="Sheet"]}[Data],
				    Promoted = Table.PromoteHeaders(Cleaning_Log, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"Step", type text}, {"Action", type text}, {"Rows_Affected", Int64.Type}, {"Reason", type text}, {"Rows_After", Int64.Type}}),
				    Result = Table.AddIndexColumn(Typed, "Log_Order", 1, 1, Int64.Type)
				in
				    Result

	annotation PBI_ResultType = Table
